repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'  # exclude markdown files
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-added-large-files
        exclude: 'uv.lock'
      - id: check-toml
      - id: detect-private-key
      - id: mixed-line-ending
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix, --preview]
